<?php

/**
 * @file
 * Contains showtime_deploy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function showtime_deploy_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_form') {
    $form['field_sales_rep']['#states'] = [
      'visible' => [
        'input[name="roles[subscriber]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_captain']['#states'] = [
      'visible' => [
        'input[name="roles[sales_rep]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_division_chair']['#states'] = [
      'visible' => [
        'input[name="roles[captain]"]' => ['checked' => TRUE],
      ],
    ];

    $form['#validate'][] = '_validate_role_pyramid';
  }
}

/**
 * Adds validation on submission values in user form.
 */
function _validate_role_pyramid(&$form, FormStateInterface $form_state) {
  if ($form_state->hasValue('roles')) {
    $roles = $form_state->getValue('roles');

    if (in_array('subscriber', $roles) && $form_state->getValue('field_sales_rep') != NULL) {
      $form_state->setErrorByName('field_sales_rep', t("Please list this user's Sales Representative."));
    }
    if (in_array('sales_rep', $roles) && $form_state->getValue('field_captain') != NULL) {
      $form_state->setErrorByName('field_captain', t("Please list this user's Captain."));
    }
    if (in_array('captain', $roles) && $form_state->getValue('field_division_chair') != NULL) {
      $form_state->setErrorByName('field_division_chair', t("Please list this user's Division Chair."));
    }
  }
}

/**
 * Implements hook_help().
 */
function showtime_deploy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the showtime_deploy module.
    case 'help.page.showtime_deploy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration and custom code for Showtime.') . '</p>';
      return $output;

    default:
  }
}
