<?php

/**
 * @file
 * Contains showtime_deploy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function showtime_deploy_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form' || $form_id == 'user_form') {
    $form['field_captain']['#states'] = [
      'visible' => [
        'input[name="roles[sales_rep]"]' => ['checked' => TRUE],
      ],
    ];
    $form['field_division_chair']['#states'] = [
      'visible' => [
        'input[name="roles[captain]"]' => ['checked' => TRUE],
      ],
    ];

    $form['#validate'][] = '_validate_role_pyramid';
  }
  elseif ($form_id == 'node_subscription_form' || $form_id == 'node_subscription_edit_form') {
    $form['field_package_adult']['#states'] = [
      'visible' => [
        'input[name=field_family_package]' => ['value' => 1],
      ],
      'required' => [
        'input[name=field_family_package]' => ['value' => 1],
      ],
    ];
    $form['field_package_child']['#states'] = [
      'visible' => [
        'input[name=field_family_package]' => ['value' => 1],
      ],
    ];

    $form['#validate'][] = '_validate_family_package';
  }
}

/**
 * Adds validation on submission values in user form.
 */
function _validate_role_pyramid(&$form, FormStateInterface $form_state) {
  $captain = ['field_captain', 0, 'target_id'];
  $chair = ['field_division_chair', 0, 'target_id'];

  // Grab user roles.
  if ($form_state->hasValue('roles')) {
    $roles = $form_state->getValue('roles');

    // Review roles.  Confirm corresponding fields are filled.
    if (in_array('sales_rep', $roles) && $form_state->getValue($captain) == NULL) {
      $form_state->setErrorByName('field_captain', t("Please list this user's Captain."));
    }
    if (in_array('captain', $roles) && $form_state->getValue($chair) == NULL) {
      $form_state->setErrorByName('field_division_chair', t("Please list this user's Division Chair."));
    }
  }
}

/**
 * Adds validation on submission values in user form.
 */
function _validate_family_package(&$form, FormStateInterface $form_state) {
  // If Family Package is no, set number of package adult tickets to 0.
  if ($form_state->getValue(['field_family_package', 0, 'value']) == "0") {
    $form_state->setValue(['field_package_adult', 0, 'value'], 0);
  }
  // Otherwise, Family Package is Yes, and we need to confirm
  // a value is entered for package adult tickets.
  elseif ($form_state->getValue(['field_package_adult', 0, 'value']) == NULL) {
    $form_state->setErrorByName('field_package_adult', t("List the number of Adult tickets for this family package."));
  }
}

/**
 * Implements hook_help().
 */
function showtime_deploy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the showtime_deploy module.
    case 'help.page.showtime_deploy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration and custom code for Showtime.') . '</p>';
      return $output;

    default:
  }
}
